

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/docker-exercise
      - /docker-exercise/node_modules
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=docker_exercise
      - NODE_ENV=development
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    command: npm run start
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docker_exercise
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: